version: 2.1

commands:
  build:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - run:
          name: Install Equals
          command: pip install -e .
  test:
    steps:
      - run:
          name: Run tests
          command: pytest -s test

orbs:
  python: circleci/python@1.5.0
  coveralls: coveralls/coveralls@1.0.6

jobs:
  python2-7:
    steps:
      - build
      - test
    docker:
      - image: cimg/python:2.7.18
  python3-10:
    docker:
      - image: cimg/python:3.10.12-node
    steps:
      - build
      - test
      - coveralls/upload:
          path_to_lcov:  .coverage
  python3-11:
    steps:
      - build
      - test
    docker:
      - image: cimg/python:3.11.4

workflows:
  run:
    jobs:
      - python2-7
      - python3-10
      - python3-11

