version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements-dev.txt
      - python/install-equals:
          name: Install Equals
          command: pip install -e .
      - run:
          name: Run tests
          command: pytest -s test

workflows:
  run:
    jobs:
      - build-and-test

